baseURL = "/"
languageCode = "en-us"
title = "Useful PoE Tools"
themesDir = "themes"
theme = "hello-friend-ng"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
PygmentsStyle = "monokai"
paginate = 10

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = false
enableGitInfo   = false
enableEmoji     = false
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"


# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    identifier = "home"

[[menu.main]]
    name = "Tools"
    url = "/docs/"
    identifier = "tools"

[[menu.main]]
    name = "Resources"
    url = "/docs/resources/"
    identifier = "resources"

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Start Here'
  homepage_intro = 'Path of Exile is a game that rewards efficiency. Spend less time looking at useless loot, confusing skill trees, and complicated item modifiers with these external tools.'
  homepage_image = '/images/poelogo.png'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  [params.homepage_meta_tags]
    meta_description = "Path of Exile tools to improve in-game efficiency."
    meta_og_title = "PoE Tools"
    meta_og_type = "website"
    meta_og_url = "https://poetools.netlify.app"
    meta_og_image = "https://i.imgur.com/Fpn4rk3.png"
    meta_og_description = "Path of Exile tools to improve in-game efficiency."


[params.author]
  name = "SJP"

 [params.footer]
    trademark = 2024
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://github.com/imsjp\">SJP</a>"
    ]