baseURL = "/"
languageCode = "en-us"
title = "Useful PoE Tools"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Tools"
    url = "/docs/"
    weight = 2

[[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 3
[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Start Here'
  homepage_intro = 'Path of Exile is a game that rewards efficiency. Spend less time looking at useless loot, confusing skill trees, and complicated item modifiers with these external tools.'
  homepage_image = '/images/poelogo.png'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Path of Exile tools to improve in-game efficiency."
    meta_og_title = "PoE Tools"
    meta_og_type = "website"
    meta_og_url = "https://poetools.netlify.app"
    meta_og_image = "https://i.imgur.com/Fpn4rk3.png"
    meta_og_description = "Path of Exile tools to improve in-game efficiency."

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
